// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteRegistry.API.Data.DAL.Data;

namespace WasteRegistry.API.Migrations
{
    [DbContext(typeof(WasteRegistrationContext))]
    [Migration("20201113054456_WasteRegistry")]
    partial class WasteRegistry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WasteRegistry.API.Data.DML.WasteRegistryTB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WasteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WasteKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WasteRegistryTB");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Voluptates labore laborum quisquam nihil ratione rem.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 3,
                            Quantity = 36,
                            QuantityUnit = "Unit2",
                            RecipientCompany = "Company2",
                            Store = "Store4",
                            WasteDate = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind1",
                            WasteType = "WasteType2"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Officia velit veniam quisquam vel quis et.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 6,
                            Quantity = 77,
                            QuantityUnit = "Unit2",
                            RecipientCompany = "Company1",
                            Store = "Store1",
                            WasteDate = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind2",
                            WasteType = "WasteType1"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Laboriosam aliquam libero quas debitis sed voluptatem.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 3,
                            Quantity = 52,
                            QuantityUnit = "Unit2",
                            RecipientCompany = "Company2",
                            Store = "Store3",
                            WasteDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind1",
                            WasteType = "WasteType1"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Molestias magni dolorum deleniti et quis sit.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 1,
                            Quantity = 128,
                            QuantityUnit = "Unit1",
                            RecipientCompany = "Company2",
                            Store = "Store5",
                            WasteDate = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind2",
                            WasteType = "WasteType2"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Porro quae ut omnis et maxime quam.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 3,
                            Quantity = 183,
                            QuantityUnit = "Unit1",
                            RecipientCompany = "Company1",
                            Store = "Store3",
                            WasteDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind1",
                            WasteType = "WasteType1"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Blanditiis sed sapiente officiis et commodi aut.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 3,
                            Quantity = 113,
                            QuantityUnit = "Unit1",
                            RecipientCompany = "Company2",
                            Store = "Store5",
                            WasteDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind2",
                            WasteType = "WasteType2"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Eligendi voluptates reiciendis nostrum autem sit autem.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 2,
                            Quantity = 53,
                            QuantityUnit = "Unit2",
                            RecipientCompany = "Company1",
                            Store = "Store4",
                            WasteDate = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind2",
                            WasteType = "WasteType1"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Ex omnis eos minima voluptates molestiae unde.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 4,
                            Quantity = 38,
                            QuantityUnit = "Unit2",
                            RecipientCompany = "Company1",
                            Store = "Store4",
                            WasteDate = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind1",
                            WasteType = "WasteType1"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Voluptatibus totam quis est voluptas ea tenetur.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 6,
                            Quantity = 94,
                            QuantityUnit = "Unit2",
                            RecipientCompany = "Company4",
                            Store = "Store1",
                            WasteDate = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind1",
                            WasteType = "WasteType2"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Expedita et molestiae sunt rerum blanditiis et.",
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1407),
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 511, DateTimeKind.Local).AddTicks(1620),
                            Month = 1,
                            Quantity = 64,
                            QuantityUnit = "Unit2",
                            RecipientCompany = "Company1",
                            Store = "Store1",
                            WasteDate = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            WasteKind = "WasteKind2",
                            WasteType = "WasteType1"
                        });
                });

            modelBuilder.Entity("WasteRegistry.API.Token.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 467, DateTimeKind.Local).AddTicks(6984),
                            FirstName = "Fredrick",
                            LastName = "Schuppe",
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 469, DateTimeKind.Local).AddTicks(5060),
                            Password = "ksa3cwsf",
                            Username = "Fredrick.Schuppe"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2020, 11, 13, 8, 44, 56, 467, DateTimeKind.Local).AddTicks(6984),
                            FirstName = "Isabel",
                            LastName = "Pollich",
                            ModifiedDate = new DateTime(2020, 11, 13, 8, 44, 56, 469, DateTimeKind.Local).AddTicks(5060),
                            Password = "uk1qcl2y",
                            Username = "Isabel62"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dummy",
                            LastName = "User",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "qwerty124",
                            Username = "DummyUser123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
